---
name: userfs
version: "{{major}}.{{minor}}.{{patch}}"
description: A system-bootstrapping automation and introspection tool.
entry: {{entry}}
requirements:
  - gitPython
  - vcorelib>=1.6.2
  - rcmpy
dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: build
    description: attempt to build a software project from its sources
  - name: custom
    description: perform a custom interaction, sourced from external hooks
  - name: fetch
    description: attempt to obtain some software from the internet
